name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x', '1.22.x' ]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out the code into the Go module directory
      uses: actions/checkout@v4
      with:
          fetch-depth: 0  # Ensure the entire history is fetched for comparison

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
      with:
        version: v1.60.3

    - name: Unit Tests with Coverage
      run: go test -race -covermode atomic -coverprofile=covprofile ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        with:
          version: v1.60.3
